# Generated by Django 4.2 on 2024-06-27 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nama Material')),
                ('unit', models.CharField(max_length=100, verbose_name='Satuan Material')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Harga Bahan')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Material',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nama Kategori Material')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskripsi')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategori Material',
                'verbose_name_plural': 'Kategori Material',
            },
        ),
        migrations.CreateModel(
            name='PK',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pk_number', models.CharField(max_length=100, unique=True, verbose_name='Nomor PK')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('execution_time', models.IntegerField(verbose_name='Waktu Pelaksanaan')),
                ('maintenance_time', models.IntegerField(verbose_name='Waktu Pemeliharaan')),
                ('bast_date', models.DateField(blank=True, null=True, verbose_name='Tanggal BAST I')),
                ('status', models.CharField(choices=[('PENGERJAAN', 'Pengerjaan'), ('PROSES_KTK', 'Proses KTK'), ('PEMBAYARAN', 'Pembayaran'), ('PEMELIHARAAN', 'Pemeliharaan'), ('SELESAI', 'Selesai')], default='PENGERJAAN', max_length=20, verbose_name='Status PK')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasi')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perintah Kerja',
                'verbose_name_plural': 'Perintah Kerja',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peran',
                'verbose_name_plural': 'Peran',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub Pekerjaan',
                'verbose_name_plural': 'Sub Pekerjaan',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Jenis Pekerjaan')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskripsi')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jenis Pekerjaan',
                'verbose_name_plural': 'Jenis Pekerjaan',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jardist.department')),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jardist.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateRAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('rab', models.FileField(help_text='Upload file RAB dalam format CSV', upload_to='static/jardist/files/rab/', verbose_name='Template RAB')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.tasktype', verbose_name='Jenis Pekerjaan')),
            ],
            options={
                'verbose_name': 'Template RAB',
                'verbose_name_plural': 'Template RAB',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100, verbose_name='Nama Pekerjaan')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nama Pelanggan')),
                ('location', models.CharField(max_length=100, verbose_name='Lokasi Pekerjaan')),
                ('execution_time', models.IntegerField(verbose_name='Waktu Pelaksanaan')),
                ('maintenance_time', models.IntegerField(verbose_name='Waktu Pemeliharaan')),
                ('rab', models.FileField(blank=True, null=True, upload_to='static/jardist/files/rab/', verbose_name='RAB')),
                ('status', models.CharField(choices=[('On Progress', 'On Progress'), ('Done', 'Done')], default='On Progress', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('pk_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.pk', verbose_name='No. PK')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.tasktype', verbose_name='Jenis Pekerjaan')),
            ],
            options={
                'verbose_name': 'Pekerjaan',
                'verbose_name_plural': 'Pekerjaan',
            },
        ),
        migrations.CreateModel(
            name='SubTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Sub Jenis Pekerjaan')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskripsi')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('task_types', models.ManyToManyField(related_name='sub_task_types', to='jardist.tasktype', verbose_name='Jenis Pekerjaan')),
            ],
            options={
                'verbose_name': 'Sub Jenis Pekerjaan',
                'verbose_name_plural': 'Sub Jenis Pekerjaan',
            },
        ),
        migrations.CreateModel(
            name='SubTaskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Harga Upah')),
                ('rab_client_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='Volume Client (RAB)')),
                ('rab_contractor_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='Volume Pemborong (RAB)')),
                ('realization_client_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='Volume Client (Realisasi)')),
                ('realization_contractor_volume', models.IntegerField(blank=True, default=0, null=True, verbose_name='Volume Pemborong (Realisasi)')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jardist.materialcategory', verbose_name='Kategori Material')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.material')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.subtask')),
            ],
            options={
                'verbose_name': 'Material Sub Pekerjaan',
                'verbose_name_plural': 'Material Sub Pekerjaan',
            },
        ),
        migrations.AddField(
            model_name='subtask',
            name='materials',
            field=models.ManyToManyField(through='jardist.SubTaskMaterial', to='jardist.material'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='sub_task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.subtasktype', verbose_name='Sub Jenis Pekerjaan'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.task', verbose_name='Pekerjaan'),
        ),
        migrations.CreateModel(
            name='SPK',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spk_number', models.CharField(max_length=100, unique=True, verbose_name='Nomor SPK')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('execution_time', models.IntegerField(verbose_name='Waktu Pelaksanaan')),
                ('maintenance_time', models.IntegerField(verbose_name='Waktu Pemeliharaan')),
                ('is_without_pk', models.BooleanField(default=False, verbose_name='Tanpa PK')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardist.department')),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surat Perjanjian Kerja',
                'verbose_name_plural': 'Surat Perjanjian Kerja',
            },
        ),
        migrations.CreateModel(
            name='PKStatusAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('PENGERJAAN', 'Pengerjaan'), ('PROSES_KTK', 'Proses KTK'), ('PEMBAYARAN', 'Pembayaran'), ('PEMELIHARAAN', 'Pemeliharaan'), ('SELESAI', 'Selesai')], max_length=20, verbose_name='Status Lama')),
                ('new_status', models.CharField(choices=[('PENGERJAAN', 'Pengerjaan'), ('PROSES_KTK', 'Proses KTK'), ('PEMBAYARAN', 'Pembayaran'), ('PEMELIHARAAN', 'Pemeliharaan'), ('SELESAI', 'Selesai')], max_length=20, verbose_name='Status Baru')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('pk_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='jardist.pk', verbose_name='No. PK')),
            ],
            options={
                'verbose_name': 'Riwayat Perubahan Status PK',
                'verbose_name_plural': 'Riwayat Perubahan Status PK',
            },
        ),
        migrations.AddField(
            model_name='pk',
            name='spk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.spk', verbose_name='SPK'),
        ),
    ]
