# Generated by Django 4.2 on 2024-06-17 04:02

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create(username='admin', password=make_password('admin123'), is_superuser=True, is_staff=True)

def remove_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser, remove_superuser),
    ]
