# Generated by Django 4.2 on 2024-06-17 04:02

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group

def add_roles(apps, schema_editor):
    Role = apps.get_model('jardist', 'Role')
    Role.objects.bulk_create([
        Role(name='staff'.title()),
        Role(name='pengawas'.title()),
        Role(name='direktur'.title()),
    ])

    for role in Role.objects.all():
        Group.objects.get_or_create(name=role.name.title())

def remove_roles(apps, schema_editor):
    Role = apps.get_model('jardist', 'Role')
    Role.objects.all().delete()
    Group.objects.all().delete()

def add_departments(apps, schema_editor):
    Department = apps.get_model('jardist', 'Department')
    Department.objects.bulk_create([
        Department(name='Departemen'.title(), description='Departemen'),
    ])

def remove_departments(apps, schema_editor):
    Department = apps.get_model('jardist', 'Department')
    Department.objects.all().delete()

def create_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create(username='admin', password=make_password('admin123'), is_superuser=True, is_staff=True)

def remove_all_users(apps, schema_editor):
    User = get_user_model()
    User.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser, remove_all_users),
        migrations.RunPython(add_roles, remove_roles),
        migrations.RunPython(add_departments, remove_departments),
    ]
