# Generated by Django 4.2 on 2024-06-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0002_initial-data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardist.tasktype', verbose_name='Jenis Pekerjaan'),
        ),
    ]
