# Generated by Django 4.2 on 2024-07-07 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jardist', '0002_initial-data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdocumentation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskdocumentation',
            name='photo',
        ),
        migrations.AddField(
            model_name='taskdocumentation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdocumentation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdocumentation',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taskdocumentation',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskDocumentationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to='static/jardist/files/task_documentations/', verbose_name='Foto')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('task_documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jardist.taskdocumentation', verbose_name='Dokumentasi Pekerjaan')),
            ],
            options={
                'verbose_name': 'Foto Dokumentasi Pekerjaan',
                'verbose_name_plural': 'Foto Dokumentasi Pekerjaan',
            },
        ),
    ]
