# Generated by Django 4.2 on 2024-06-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0002_initial-data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spk',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardist.department'),
        ),
    ]
