# Generated by Django 4.2 on 2024-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0002_initial-data'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('On Progress', 'On Progress'), ('Done', 'Done')], default='On Progress', max_length=20, verbose_name='Status'),
        ),
    ]
