# Generated by Django 4.2 on 2024-07-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0003_document_created_at_document_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkarchivedocument',
            name='upload_date',
        ),
    ]
