# Generated by Django 4.2 on 2024-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0003_alter_task_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtasktype',
            name='task_type',
        ),
        migrations.AddField(
            model_name='subtasktype',
            name='task_types',
            field=models.ManyToManyField(related_name='sub_task_types', to='jardist.tasktype', verbose_name='Jenis Pekerjaan'),
        ),
    ]
