# Generated by Django 4.2 on 2024-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0003_remove_taskdocumentation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pickup_file',
            field=models.FileField(upload_to='archive/pickup/', verbose_name='File Dokumen Pengambilan Barang'),
        ),
        migrations.AlterField(
            model_name='document',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='archive/proof/', verbose_name='File Bukti Pengambilan Barang'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rab',
            field=models.FileField(blank=True, null=True, upload_to='rab/', verbose_name='RAB'),
        ),
        migrations.AlterField(
            model_name='taskdocumentationphoto',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='taskdocumentationphoto',
            name='photo',
            field=models.FileField(upload_to='task_documentation/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='templaterab',
            name='rab',
            field=models.FileField(help_text='Upload file RAB dalam format CSV', upload_to='rab/', verbose_name='Template RAB'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdocumentation',
            unique_together={('task', 'location')},
        ),
    ]
