# Generated by Django 4.2 on 2024-06-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0004_alter_subtaskmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskmaterial',
            name='labor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Harga Upah'),
        ),
    ]
