# Generated by Django 4.2 on 2024-06-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardist', '0005_alter_subtaskmaterial_labor_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskmaterial',
            name='rab_client_volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Volume Client (RAB)'),
        ),
        migrations.AlterField(
            model_name='subtaskmaterial',
            name='rab_contractor_volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Volume Pemborong (RAB)'),
        ),
        migrations.AlterField(
            model_name='subtaskmaterial',
            name='realization_client_volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Volume Client (Realisasi)'),
        ),
        migrations.AlterField(
            model_name='subtaskmaterial',
            name='realization_contractor_volume',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Volume Pemborong (Realisasi)'),
        ),
    ]
